exclude_patterns:
  - '**/node_modules/'
  - '**/*.d.ts'
  - '**/*.spec.ts'
  - '**/*.spec.js'
  - '**/*.json'
  - '**/*.lock'
  - '**/*.enc'
  - '**/*.yml'
  - '**/.*.yml'
  - '**/*.md'
  - '**/.nycrc'
  - '**/.prettierrc'
  - '**/.gitignore'
  - '**/.editorconfig'
  - '**/.dockerignore'
  - '**/.babelrc'
  - 'LICENSE'
  - 'Dockerfile'
  - 'mocha.init.js'
  - 'src/controllers/graphql/schemas/resolvers/*.ts'
  - 'src/tests/**/*.ts'
  - 'src/index.ts'