exclude_patterns:
  - '**/node_modules/'
  - '**/*.d.ts'
  - '**/*.spec.ts'
  - '**/*.spec.js'
  - 'src/schemas/resolvers/*.ts'
  - 'src/tests/**/*.ts'
  - '**/*.json'
  - '**/*.lock'
  - '**/*.enc'
  - '**/*.yml'
  - '**/*.md'
  - 'LICENSE'
  - '.prettierrc'
  - '.gitignore'
  - '.editorconfig'
  - '.dockerignore'
  - '.babelrc'