sudo: true
language: node_js
node_js:
  - "8"
cache:
  npm: true
  yarn: true

branches:
  only:
    - develop

before_install:
  - yarn global add serverless

install:
  - yarn

script:
  - yarn build

after_script:
  - yarn deploy:gcp
# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
