sudo: true
language: node_js
node_js:
  - "8"
cache:
  npm: true
  yarn: true

branches:
  only:
    - develop

before_install:
  - openssl aes-256-cbc -K $encrypted_076465f680f2_key -iv $encrypted_076465f680f2_iv -in keyfile.json.enc -out keyfile.json -d
  - yarn global add serverless

install:
  - yarn

before_script:
  - yarn build

script:
  - yarn test:js
  # - yarn test:ts

deploy:
  provider: script
  script: yarn deploy:gcp
  skip_cleanup: true
  on:
    branch: develop
